### ISSUE TITLE
Add addin to website to allow for automatic documentation

### ISSUE THREAD

**Issue by gep13** [SharpeRAD/Cake.AWS.CloudFront#2]
i.e. get your addin listed here:

http://cakebuild.net/addins

Have a look at this PR:

cake-build/website#152

This assumes that you have added XML Documentation to your addin, as described here:

http://cakebuild.net/docs/contributing/documentation

Let me know if you have any questions. Thanks!

**Comment by Jericho** [comment]
The YAML for this addin was added to the Cake web site in [March 2017](https://github.com/cake-build/website/commit/417919decc312ec1e14459c6c497eba39ff6fda4#diff-529603b493b704934ee6fa716541903f). I think it's safe to close this issue.

**Comment by gep13** [comment]
@jericho thanks for following up with this!
